name: Generate Snake Game

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake game (custom colors)
        uses: Platane/snk@v3
        with:
          github_user_name: RAPIDENN
          outputs: |
            output/github-contribution-grid-snake.svg?color_snake=#00FFF0&color_dots=#1E2A35,#243748,#2F455A
            output/github-contribution-grid-snake-dark.svg?color_snake=#00FFF0&color_dots=#1E2A35,#243748,#2F455A
            output/github-contribution-grid-snake.gif

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🐍 Update snake game (custom theme)"
          file_pattern: "output/*"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
